name: Publish to Nuget

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish to Nuget
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: TrendFox.Templates.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        TAG_COMMIT: false
        VERSION_REGEX: <PackageVersion>(.*)<\/PackageVersion>
